# Generated by Django 4.2 on 2024-10-09 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0003_alter_postmodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='price',
            field=models.TextField(),
        ),
    ]
